# -*- coding: utf-8 -*-
"""update_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLmg8-1P-Hi6U0ktOeSDuHB0QTKSAG1D
"""

import pandas as pd
import requests
from datetime import datetime, timedelta
import yfinance as yf
import os

# Setup
NEWSAPI_KEY = os.getenv("NEWSAPI_KEY")
NEWS_CSV = "merged_sentiment_cleaned_202005_202504.csv"
PRICE_CSV = "sp500_price_202005_202504.csv"

# News data
def fetch_news():
    today = datetime.utcnow().date()
    yesterday = today - timedelta(days=1)

    url = (
        f"https://newsapi.org/v2/everything?"
        f"q=S%26P%20500&from={yesterday}&to={today}&"
        f"language=en&sortBy=publishedAt&pageSize=100&apiKey={NEWSAPI_KEY}"
    )

    r = requests.get(url)
    data = r.json()

    rows = []
    for article in data.get("articles", []):
        rows.append({
            "date": article["publishedAt"][:10],
            "title": article["title"],
            "description": article["description"],
            "content": article["content"],
            "related": "S&P 500",
            "source": article["source"]["name"]
        })

    return pd.DataFrame(rows)

# S&P 500 close price
def fetch_price():
    end = datetime.utcnow().date()
    start = end - timedelta(days=3)
    df = yf.download("^GSPC", start=start, end=end)
    df = df.reset_index()[["Date", "Close"]]
    df.columns = ["date", "close"]
    df["date"] = pd.to_datetime(df["date"]).dt.date
    return df

# Updata CSV file
def update_csv():
    news_df = fetch_news()
    price_df = fetch_price()

    if not news_df.empty:
        old_news = pd.read_csv(NEWS_CSV)
        combined_news = pd.concat([old_news, news_df], ignore_index=True).drop_duplicates()
        combined_news.to_csv(NEWS_CSV, index=False)

    if not price_df.empty:
        old_price = pd.read_csv(PRICE_CSV)
        combined_price = pd.concat([old_price, price_df], ignore_index=True).drop_duplicates()
        combined_price.to_csv(PRICE_CSV, index=False)

if __name__ == "__main__":
    update_csv()